### PR TITLE
Updated the gradebook services

### PR DESCRIPTION
**Pull request by Luis-Jimenez-dev**

### CODE REVIEW

**Review by TidalWings — APPROVED** [review]
The logic looks good, some comments for clarity for certain functions would be appreciated.

**Review by TidalWings — APPROVED** [review]
Looks good to me.

**Review by Luis-Jimenez-dev — COMMENTED** [review]
Added comments explaining the new functions

**Review by TidalWings — APPROVED** [review]
Also looks good to me.

**Pull request merged**
